# Generated by Django 3.0.7 on 2020-07-22 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateField(default=datetime.date(2020, 7, 22)),
        ),
    ]
